import { AzureFunction, Context, HttpRequest } from "@azure/functions";
import { Client } from "pg";
import { config } from "../services/database/database.config";
import { employee_docs } from "./model";

const httpTrigger: AzureFunction = async function (
  context: Context,
  req: HttpRequest
): Promise<void> {
  const db = new Client(config);

  try {
    const employee_doc: employee_docs = req.body;
    let query = `
    INSERT INTO 
                "Employees_Documents" 
                (
                "category",
                "passport_country",
                "passport_number",
                "passport_expiration_date",
                "passport_doc",
                "passport_sign",
                "passport_disclaimer,
                "approval_letter_date",
                "approval_letter_doc",
                "approval_letter_sign",
                "approval_letter_disclaimer",
                "contract_date",
                "contract_doc",
                "contract_sign",
                "contract_disclaimer",
                "b797_number",
                "b797_expiration_date",
                "b797_doc",
                "b797_sign",
                "b797_disclaimer",
                "dot_physical_name",
                "dot_physical_expiration_date",
                "dot_physical_issue_date",
                "dot_physical_doc",
                "dot_physical_sign",
                "dot_physical_disclaimer",
                "drug_test_name",
                "drug_test_expiration_date",
                "drug_test_issue_date",
                "drug_test_doc",
                "drug_test_sign",
                "drug_test_disclaimer",
                "auto_license_state",
                "auto_license_number",
                "auto_license_expiration_date",
                "auto_license_issue_date",
                "auto_license_doc",
                "auto_license_sign",
                "auto_license_disclaimer",
                "cdl_license_state",
                "cdl_license_number",
                "cdl_license_issue_date",
                "cdl_license_doc",
                "cdl_license_sign",
                "cdl_license_disclaimer",
                "work_agreement_date",
                "work_agreement_doc",
                "work_agreement_sign",
                "work_agreement_disclaimer",
                "itinerary_date",
                "itinerary_doc",
                "itinerary_sign",
                "itinerary_disclaimer",
                "visa_control_number",
                "visa_issue_date",
                "visa_expiration_date",
                "visa_nationality",
                "visa_red_stamped_no",
                "visa_issue_post",
                "visa_doc",
                "visa_sign",
                "visa_disclaimer",
                "i9_date",
                "i9_doc",
                "i9_sign",
                "i9_disclaimer",
                "i94_date",
                "i94_doc",
                "i94_number",
                "i94_sign",
                "i94_disclaimer",
                "cert_arrival_date",
                "cert_first_day",
                "cert_doc",
                "cert_sign",
                "cert_disclaimer",
                "department_last_day",
                "department_departure_date",
                "department_doc",
                "department_sign",
                "department_disclaimer",
                "handbook_date",
                "handbook_doc",
                "handbook_sign",
                "handbook_disclaimer",
                "rules_date",
                "rules_doc",
                "rules_sign",
                "rules_disclaimer",
                "drug_policy_date",
                "drug_policy_doc",
                "drug_policy_sign",
                "drug_policy_disclaimer",
                "reprimand_policy_date",
                "reprimand_policy_doc",
                "reprimand_policy_sign",
                "reprimand_policy_disclaimer",
                "departure_date",
                "departure_doc",
                "departure_sign",
                "departure_disclaimer",
                "bank_acc_name",
                "bank_acc_routing",
                "bank_acc_account",
                "bank_acc_doc",
                "bank_acc_sign",
                "bank_acc_disclaimer",
                "social_sec_number",
                "social_sec_name",
                "social_sec_doc",
                "social_sec_sign",
                "social_sec_disclaimer",
                "w4_name",
                "w4_doc",
                "w4_sign",
                "w4_disclaimer",
                "created_at" 
                )
      VALUES      
                (
                '${employee_doc.category}',
                '${employee_doc.passport_country}',
                '${employee_doc.passport_number}',
                '${employee_doc.passport_expiration_date}' ::date,
                '${employee_doc.passport_doc}',
                '${employee_doc.passport_sign}',
                '${employee_doc.passport_disclaimer}',
                '${employee_doc.approval_letter_date}' ::date,
                '${employee_doc.approval_letter_doc}',
                '${employee_doc.approval_letter_sign}',
                '${employee_doc.approval_letter_disclaimer}',
                '${employee_doc.contract_date}' ::date,
                '${employee_doc.contract_doc}',
                '${employee_doc.contract_sign}',
                '${employee_doc.contract_disclaimer}',
                '${employee_doc.b797_number}',
                '${employee_doc.b797_expiration_date}' ::date,
                '${employee_doc.b797_doc}',
                '${employee_doc.b797_sign}',
                '${employee_doc.b797_disclaimer}',
                '${employee_doc.dot_physical_name}',
                '${employee_doc.dot_physical_expiration_date}' ::date,
                '${employee_doc.dot_physical_issue_date}' ::date,
                '${employee_doc.dot_physical_doc}',
                '${employee_doc.dot_physical_sign}',
                '${employee_doc.dot_physical_disclaimer}',
                '${employee_doc.drug_test_name}',
                '${employee_doc.drug_test_expiration_date}' ::date,
                '${employee_doc.drug_test_issue_date}' ::date,
                '${employee_doc.drug_test_doc}',
                '${employee_doc.drug_test_sign}',
                '${employee_doc.drug_test_disclaimer}',
                '${employee_doc.auto_license_state}',
                '${employee_doc.auto_license_number}',
                '${employee_doc.auto_license_expiration_date}' ::date,
                '${employee_doc.auto_license_issue_date}' ::date,
                '${employee_doc.auto_license_doc}',
                '${employee_doc.auto_license_sign}',
                '${employee_doc.auto_license_disclaimer}',
                '${employee_doc.cdl_license_state}',
                '${employee_doc.cdl_license_number}',
                '${employee_doc.cdl_license_issue_date}' ::date,
                '${employee_doc.cdl_license_doc}',
                '${employee_doc.cdl_license_sign}',
                '${employee_doc.cdl_license_disclaimer}',
                '${employee_doc.work_agreement_date}' ::date,
                '${employee_doc.work_agreement_doc}',
                '${employee_doc.work_agreement_sign}',
                '${employee_doc.work_agreement_disclaimer}',
                '${employee_doc.itinerary_date}' ::date,
                '${employee_doc.itinerary_doc}',
                '${employee_doc.itinerary_sign}',
                '${employee_doc.itinerary_disclaimer}',
                '${employee_doc.visa_control_number}',
                '${employee_doc.visa_issue_date}' ::date,
                '${employee_doc.visa_expiration_date}' ::date,
                '${employee_doc.visa_nationality}',
                '${employee_doc.visa_red_stamped_no}',
                '${employee_doc.visa_issue_post}',
                '${employee_doc.visa_doc}',
                '${employee_doc.visa_sign}',
                '${employee_doc.visa_disclaimer}',
                '${employee_doc.i9_date}' ::date,
                '${employee_doc.i9_doc}',
                '${employee_doc.i9_sign}',
                '${employee_doc.i9_disclaimer}',
                '${employee_doc.i94_date}' ::date,
                '${employee_doc.i94_doc}',
                '${employee_doc.i94_number}',
                '${employee_doc.i94_sign}',
                '${employee_doc.i94_disclaimer}',
                '${employee_doc.cert_arrival_date}' ::date,
                '${employee_doc.cert_first_day}',
                '${employee_doc.cert_doc}',
                '${employee_doc.cert_sign}',
                '${employee_doc.cert_disclaimer}',
                '${employee_doc.department_last_day}',
                '${employee_doc.department_departure_date}' ::date, 
                '${employee_doc.department_doc}',
                '${employee_doc.department_sign}',
                '${employee_doc.department_disclaimer}',
                '${employee_doc.handbook_date}' ::date,
                '${employee_doc.handbook_doc}',
                '${employee_doc.handbook_sign}',
                '${employee_doc.handbook_disclaimer}',
                '${employee_doc.rules_date}' ::date,
                '${employee_doc.rules_doc}',
                '${employee_doc.rules_sign}',
                '${employee_doc.rules_disclaimer}',
                '${employee_doc.drug_policy_date}' ::date,
                '${employee_doc.drug_policy_doc}',
                '${employee_doc.drug_policy_sign}',
                '${employee_doc.drug_policy_disclaimer}',
                '${employee_doc.reprimand_policy_date}' ::date,
                '${employee_doc.reprimand_policy_doc}',
                '${employee_doc.reprimand_policy_sign}',
                '${employee_doc.reprimand_policy_disclaimer}',
                '${employee_doc.departure_date}' ::date,
                '${employee_doc.departure_doc}',
                '${employee_doc.departure_sign}',
                '${employee_doc.departure_disclaimer}',
                '${employee_doc.bank_acc_name}',
                '${employee_doc.bank_acc_routing}',
                '${employee_doc.bank_acc_account}',
                '${employee_doc.bank_acc_doc}',
                '${employee_doc.bank_acc_sign}',
                '${employee_doc.bank_acc_disclaimer}',
                '${employee_doc.social_sec_number}',
                '${employee_doc.social_sec_name}',
                '${employee_doc.social_sec_doc}',
                '${employee_doc.social_sec_sign}',
                '${employee_doc.social_sec_disclaimer}',
                '${employee_doc.w4_name}',
                '${employee_doc.w4_doc}',
                '${employee_doc.w4_sign}',
                '${employee_doc.w4_disclaimer}',
                'now()'
                );
    `;

    db.connect();
    await db.query(query);
    db.end();
    context.res = {
      status: 200,
      body: {
        message: "Your form has been submitted successfully.",
      },
    };

    context.done();
    return;
  } catch (error) {
    db.end();
    context.res = {
      status: 500,
      body: {
        message: error.message,
      },
    };
    return;
  }
};

export default httpTrigger;
