export interface applicant {
  id?: string;
  first_name: string;
  last_name: string;
  email: string;
  cell_phone_number: string;
  home_phone_number: string;
  calendar_year: string;
  languages: string;
  date_of_birth: string;
  marital_status: string;
  address_1: string;
  address_2: string;
  postal_code: string;
  country: string;
  county: string;
  city: string;
  self_rating: string;
  us_citizen: boolean;
  tractor_license: boolean;
  passport: boolean;
  avatar: string
  resume: string
  question_1: string
  question_2: string
  question_3: string
  question_4: string
  question_5: string
  work_experience_description: string
  recent_job: string
  supervisor: string
  supervisor_contact: string
  degree_name: string
  institute_name: string
  education: string
  blood_group: string
  reason_for_applying: string
  first_call_remarks: string
  first_call_ranking: string
  first_interviewer_id: string
  second_call_remarks: string
  second_call_ranking: string
  second_interviewer_id: string
  third_call_remarks: string
  third_call_ranking: string
  third_interviewer_id: string
  reference_call_remarks: string
  reference_call_ranking: string
  reference_interviewer_id: string
  status_step: string
  status_message: string
  stepOneStatusDate: string
  stepTwoStatusDate: string
  stepThreeStatusDate: string
  stepFourStatusDate: string
  stepFiveStatusDate: string
  stepSixStatusDate: string
  stepSevenStatusDate: string
  stepEightStatusDate: string
  stepNineStatusDate: string
  stepTenStatusDate: string
  stepElevenStatusDate: string
  stepTwelveStatusDate: string
  stepThirteenStatusDate: string
}
