export interface beginningOfDay {
    id?: string;
    employeeId: string;
    machineryId?: string;
    beginningEngineHours?: string;
    endingEngineHours?: string;
    acresCompleted?: string;
    gpsAcres?: string;
    hoursWorked?: string;
    notes?: string;
    workOrderId?: number;
    dwr_type: string;
    beginning_separator_hours?: string;
    ending_separator_hours?: string;
    field_id?: string;
    field_acres?: string;
    truck_id?: string;
    crew_chief?: string;
    truck_company?: string;
    begining_odometer_miles?: string;
    ending_odometer_miles?: string;
    supervisor_id?: string;
    state?: string;
    apprTaskId?: string;
    notesOther?: string;
    module?: string;
    dwrId?: string;
    trainee_record_id: string;
}